# pictures for user public profile
VideoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.VideoBucket.name}

VideoBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref VideoBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: "*"
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.VideoBucket.name}/*